---
deployment:
  tasks:
    - export DEPLOYPATH=/home/iieciubat/iiec.iubat.edu/iiecOld
    # Copy all files and directories within the current directory (excluding .git)
    - /bin/rsync -avz --exclude=.git . $DEPLOYPATH
